apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: server
    url: https://eu-central-1-1.aws.cloud2.influxdata.com
    orgId: vvvegero97@gmail.com
    access_token: $INFLUX_TOKEN  ####??????????
    default_bucket: $BUCKET_NAME ###?????????
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    user: admin
    password: password
    database: db
    basicAuth: false
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true
