version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}
  # influxdb_data: {}

services:

  myapp:
    image: mydotnet:latest
    container_name: myapp
    ports:
      - 5000:5000
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - myapp
    restart: unless-stopped

  # db:
  #   image: influxdb:latest
  #   container_name: db
  #   environment:
  #     - INFLUXDB_DB=prometheus
  #     - INFLUXDB_ADMIN_USER=admin
  #     - INFLUXDB_ADMIN_PASSWORD=password
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - influxdb_data:/var/lib/influxdb
  #   depends_on:
  #     - cadvisor
  #   restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - cadvisor
    ports:
      - 8125:8125

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - db
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    # user: "472" #????
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./grafana-provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
