scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: myapp
  scrape_interval: 5s
  static_configs:
    - targets:
      - myapp:5000
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
    - targets:
        - 'localhost:9090'
remote_write:
 - url: "http://localhost:1234/receive"