---
- name: My Super Playbook
  hosts: prod
  become: yes
  
  vars:
    mytext: "YOU'VE BEEN GNOMED KEKW!"

  tasks:
  - name: Ping test
    ping:

  - include: create_folders.yml
  - include: create_files.yml mytext="NEVER GONNA GIVE YOU UP"
    
#import is read in 'compilation' of yml, include - after


