---
- name: Ansible Handling
  hosts: staging_DB
  become: yes


  tasks:
    - name: Task Number1
      yum: name=treeeee state=latest
      ignore_errors: yes

    - name: Task Number2
      shell: echo Hello World!
      register: results
      failed_when: results.rc == 0
      

    - debug:
        var: results

    - name: Task Number3
      shell: echo Privet Mir!!!

