---
- name: Install Apache and Upload my web page
  hosts: staging_DB
  become: yes

  vars:
   source_file: ./MyWebsite/index.html
   destin_file: /var/www/html


  tasks:
  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - block:    # =====Block for RedHat=====

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest
    
      - name: Copy my web page to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache RedHat
     
      - name: Start Web Server service for RedHat
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"


  - block:    # =====Block for UBUNTU=====

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Copy my web page to Servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache Debian

      - name: Start Web Server service for Debian
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted

